# Generated by Django 4.2.15 on 2024-09-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_package_image_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_name',
            new_name='company',
        ),
    ]
