# Generated by Django 4.2.15 on 2024-09-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ManyToManyField(to='package.feature')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.custom'),
        ),
    ]
