# Generated by Django 4.2.17 on 2025-01-25 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_category_feature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='images/icons', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
