# Generated by Django 4.2.17 on 2025-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_alter_package_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.AddField(
            model_name='package',
            name='most_pop',
            field=models.BooleanField(default=False),
        ),
    ]
