# Generated by Django 4.2.17 on 2025-01-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_alter_package_options_package_most_pop'),
        ('project', '0007_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.category'),
        ),
    ]
