# Generated by Django 4.2.15 on 2024-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
